import React, {useState} from "react";
import {Badge, Layout, Menu, MenuProps} from "antd";
import Head from "next/head";
import Link from "next/link";

type Props = {children?: React.ReactNode; title: string};
type MenuItem = Required<MenuProps>["items"][number];
function getItem(
  label: React.ReactNode,
  key: React.Key,
  icon?: React.ReactNode,
  children?: MenuItem[]
): MenuItem {
  return {
    label,
    key,
    icon,
    children,
  } as MenuItem;
}

const AdminLayouts = ({children, title}: Props) => {
  const [collapsed, setCollapsed] = useState(false);
  const {Header, Content, Footer, Sider} = Layout;

  const items: MenuItem[] = [
    getItem(<Link href="/admin/dashboard">Dashboard</Link>, "/admin"),
    getItem(<Link href="/admin/order">Order</Link>, "/admin/order"),
    getItem(<Link href="/admin/customer">Customer</Link>, "/admin/customer"),
    getItem(<Link href="/admin/product">Product</Link>, "/admin/product"),
  ];

  return (
    <>
      <Head>
        <title>{title ? title + " - REPLIQ MART" : "REPLIQ MART"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Layout style={{minHeight: "100vh"}}>
          <Sider
            collapsible
            collapsed={collapsed}
            onCollapse={(value) => setCollapsed(value)}
          >
            <div
              style={{
                height: 32,
                margin: 16,
              }}
            >
              <Link legacyBehavior href="/admin">
                <a className="text-lg font-bold text-slate-300">REPLIQ ADMIN</a>
              </Link>
            </div>
            <Menu
              theme="dark"
              defaultSelectedKeys={["1"]}
              mode="vertical"
              items={items}
            />
          </Sider>
          <Layout className="site-layout">
            <Header
              style={{
                padding: 0,
                position: "sticky",
                top: 0,
                zIndex: 1,
                width: "100%",
              }}
            />
            <Content
              className="container m-auto mt-4 bg-white p-6"
              style={{minHeight: "100vh"}}
            >
              {children}
            </Content>
            <Footer className="flex justify-center items-center h-10">{`REPLIQ ASSESSMENT - DEVELOPED WITH ❤️ BY FAHIM SHAHRIAR`}</Footer>
          </Layout>
        </Layout>
      </div>
    </>
  );
};

export default AdminLayouts;
