import React from "react";
import {Layout, Menu, MenuProps} from "antd";
import Head from "next/head";
import Link from "next/link";
import {ShoppingCartOutlined, UserOutlined} from "@ant-design/icons";

type Props = {children: React.ReactNode; title: string};
const {Header, Content, Footer} = Layout;
type MenuItem = Required<MenuProps>["items"][number];
function getItem(
  label: React.ReactNode,
  key: React.Key,
  icon?: React.ReactNode,
  children?: MenuItem[]
): MenuItem {
  return {
    label,
    key,
    icon,
    children,
  } as MenuItem;
}

function Layouts({children, title}: Props) {
  const items: MenuItem[] = [
    getItem(<Link href="/">Men's Product</Link>, "Men's Product"),
    getItem(<Link href="/">Women's Product</Link>, "Women's Product"),
    getItem(<Link href="/">Kids Product</Link>, "Kids Product"),
    getItem(<Link href="/">Digital Product</Link>, "Digital Product"),
    getItem(<Link href="/">Home & Lifestyle</Link>, "Home & Lifestyle"),
    getItem(<Link href="/">Babies & Toys</Link>, "Babies & Toys"),
    getItem(<Link href="/">Groceries</Link>, "Groceries"),
    getItem(<Link href="/">Sports Product</Link>, "Sports Product"),
    getItem(<Link href="/">Watch</Link>, "Watch"),
    getItem(<Link href="/">Accessories</Link>, "Accessories"),
    getItem(<Link href="/">Home Appliances</Link>, "Home Appliances"),
    getItem(
      <Link legacyBehavior href="/cart">
        <a className="text-base font-bold text-slate-200">Cart</a>
      </Link>,
      "Cart",
      <ShoppingCartOutlined />
    ),
    getItem(
      <Link legacyBehavior href="/login">
        <a className="text-base font-bold text-slate-200">Login</a>
      </Link>,
      "Login",
      <UserOutlined />
    ),
  ];
  return (
    <>
      <Head>
        <title>{title ? title + " - REPLIQ MART" : "REPLIQ MART"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Layout>
          <Header
            style={{position: "sticky", top: 0, zIndex: 1, width: "100%"}}
          >
            <div
              style={{
                float: "left",
                marginRight: "1rem",
              }}
            >
              <a className="text-lg font-bold text-slate-300">REPLIQ MART</a>
            </div>
            <Menu theme="dark" mode="horizontal" items={items} />
          </Header>
          <Content
            className="container m-auto mt-4 bg-white p-6"
            style={{minHeight: "100vh"}}
          >
            {children}
          </Content>

          <Footer className="flex justify-center items-center h-10">{`REPLIQ ASSESSMENT - DEVELOPED WITH ❤️ BY FAHIM SHAHRIAR`}</Footer>
        </Layout>
      </div>
    </>
  );
}

export default Layouts;
